### ISSUE TITLE
Asking player for their preferred language.

### ISSUE THREAD

**Issue by WraitheDX** [WraitheDX/realms_shattered#16]
- [x] Add player_language_get() function to UserInput class.
- [x] Add config_save() and config_load functions to FileIO class.

Player should only be asked their preferred language if there is no config file, or the language saved in the config file is invalid.
Config file should only be saved if there is a change to be saved, or if one does not exist.

**Comment by Danyaaa** [comment]
I would like to work on this one.

**Comment by WraitheDX** [comment]
That is wonderful, thank you so much!
I leave for work soon, but I am on Discord all day, so please let me know if you need anything!
https://discord.gg/6aW7DFB

**Comment by WraitheDX** [comment]
I did just push and merge my last commit for the morning, which added the config file + saving/loading, and writing a vector of strings out to a file from FileIO. This will almost certainly affect what you are working on, so please keep that in mind, and maybe re-pull the main branch. Take care!

**Comment by Danyaaa** [comment]
That's helpful. Thanks
