### ISSUE TITLE
Add Linux support

### ISSUE THREAD

**Issue by WraitheDX** [WraitheDX/realms_shattered#9]
For now, just mirroring the functionality found in the platform_windows header and source, and adding the abstracted calls to the platform header and source would be wonderful.

**Comment by Satharus** [comment]
I am working on this issue right now :D

**Comment by WraitheDX** [comment]
That is wonderful, thank you! ^ ^

**Comment by Satharus** [comment]
@WraitheDX  

There's a slight problem, getting the terminal cursor position and setting the window title in Linux are usually not possible without using nCurses which is an external library and a little bit of a hassle to work with.

are these function needed?

**Comment by WraitheDX** [comment]
@Sarathus
Bummer, thank you for the heads up!

The window title is not a big deal at all, but setting the cursor position is a must. Are there any non-curses workarounds?

**Comment by Satharus** [comment]
No worries!

Don't worry about setting the cursor position, that works fine. The problem is in getting the cursor position. 

However I am taking a look right now to see if there are any workarounds :D

**Comment by WraitheDX** [comment]
Wonderful!
Is obtaining the console's buffer size an issue? A lot of code requires that info.

**Comment by Satharus** [comment]
The size works fine yeah :D Shouldn't be an issue.

**Comment by WraitheDX** [comment]
@Satharus 

Thank you so much, it is very exciting to have my first merge from a contributor!

**Comment by Satharus** [comment]
No need at all! 

Glad that it is useful :D 

Good luck with your project, I'll definitely be following it!
